#pragma once

#define OBS_BROWSER_VERSION "1.30.1.2"
#define OBS_BROWSER_AGENT "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/" MAKE_STRING(CHROME_VERSION_MAJOR) "." MAKE_STRING(CHROME_VERSION_MINOR) "." MAKE_STRING(CHROME_VERSION_BUILD) "." MAKE_STRING(CHROME_VERSION_PATCH) " Safari/537.36 Streamlabs/" OBS_BROWSER_VERSION
